/* Generated By:JavaCC: Do not edit this line. AnalizadorSintacticoTinyConstants.java */
package asint;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AnalizadorSintacticoTinyConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int letra = 1;
  /** RegularExpression Id. */
  int digito = 2;
  /** RegularExpression Id. */
  int decimal = 3;
  /** RegularExpression Id. */
  int exponente = 4;
  /** RegularExpression Id. */
  int pa = 5;
  /** RegularExpression Id. */
  int pc = 6;
  /** RegularExpression Id. */
  int or = 7;
  /** RegularExpression Id. */
  int and = 8;
  /** RegularExpression Id. */
  int not = 9;
  /** RegularExpression Id. */
  int men = 10;
  /** RegularExpression Id. */
  int num = 11;
  /** RegularExpression Id. */
  int bool = 12;
  /** RegularExpression Id. */
  int separador = 13;
  /** RegularExpression Id. */
  int puntoComa = 16;
  /** RegularExpression Id. */
  int numeroReal = 17;
  /** RegularExpression Id. */
  int identificador = 18;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<letra>",
    "<digito>",
    "<decimal>",
    "<exponente>",
    "\"(\"",
    "\")\"",
    "\"or\"",
    "\"and\"",
    "\"not\"",
    "\"men\"",
    "\"num\"",
    "\"bool\"",
    "\"&&\"",
    "<token of kind 14>",
    "<token of kind 15>",
    "\";\"",
    "<numeroReal>",
    "<identificador>",
    "\"=\"",
    "\"+\"",
    "\"-\"",
    "\"<\"",
    "\"<=\"",
    "\"==\"",
    "\">=\"",
    "\">\"",
    "\"*\"",
    "\"/\"",
    "\"-u\"",
  };

}
