
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Sat Jun 23 23:47:39 CEST 2018
//----------------------------------------------------

package cup;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int PCIERRE = 21;
  public static final int SEP_ENTRADA = 18;
  public static final int AND = 10;
  public static final int MAYOR_IGUAL_QUE = 14;
  public static final int IGUAL = 19;
  public static final int OR = 9;
  public static final int PAPERTURA = 20;
  public static final int FIN_LINEA = 17;
  public static final int MENOR_IGUAL_QUE = 13;
  public static final int SUMA = 8;
  public static final int NOT = 4;
  public static final int IGNORABLE = 25;
  public static final int VARIABLE = 22;
  public static final int TRUE = 2;
  public static final int MAYOR_QUE = 12;
  public static final int NUM = 23;
  public static final int MENOR_QUE = 11;
  public static final int IGUAL_IGUAL = 15;
  public static final int DISTINTO = 16;
  public static final int EOF = 0;
  public static final int DIV = 6;
  public static final int FALSE = 3;
  public static final int error = 1;
  public static final int BOOL = 24;
  public static final int MUL = 7;
  public static final int VALOR = 26;
  public static final int RESTA = 5;
}

