
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Jun 11 18:55:30 CEST 2018
//----------------------------------------------------

package asint;

/** CUP generated class containing symbol constants. */
public class UnidadLexica {
  /* terminals */
  public static final int GEQ = 10;
  public static final int AND = 14;
  public static final int IS = 7;
  public static final int LT = 11;
  public static final int PLUS = 17;
  public static final int OR = 15;
  public static final int NOT = 16;
  public static final int TRUE = 22;
  public static final int GT = 9;
  public static final int ID = 5;
  public static final int PCL = 25;
  public static final int POP = 24;
  public static final int EOL = 3;
  public static final int NUM = 4;
  public static final int EOF = 0;
  public static final int DIV = 20;
  public static final int FALSE = 23;
  public static final int MINUS = 18;
  public static final int error = 1;
  public static final int EQ = 8;
  public static final int LREAL = 21;
  public static final int LEQ = 12;
  public static final int BOOL = 6;
  public static final int SPROG = 2;
  public static final int MUL = 19;
  public static final int NEQ = 13;
}

