/* Generated By:JavaCC: Do not edit this line. AnalizadorSintacticoTinyConstants.java */
package asint;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AnalizadorSintacticoTinyConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int letra = 1;
  /** RegularExpression Id. */
  int digito = 2;
  /** RegularExpression Id. */
  int decimal = 3;
  /** RegularExpression Id. */
  int exponente = 4;
  /** RegularExpression Id. */
  int pa = 5;
  /** RegularExpression Id. */
  int pc = 6;
  /** RegularExpression Id. */
  int or = 7;
  /** RegularExpression Id. */
  int and = 8;
  /** RegularExpression Id. */
  int not = 9;
  /** RegularExpression Id. */
  int men = 10;
  /** RegularExpression Id. */
  int t = 11;
  /** RegularExpression Id. */
  int f = 12;
  /** RegularExpression Id. */
  int num = 13;
  /** RegularExpression Id. */
  int bool = 14;
  /** RegularExpression Id. */
  int separador = 15;
  /** RegularExpression Id. */
  int puntoComa = 18;
  /** RegularExpression Id. */
  int numeroReal = 19;
  /** RegularExpression Id. */
  int identificador = 20;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<letra>",
    "<digito>",
    "<decimal>",
    "<exponente>",
    "\"(\"",
    "\")\"",
    "\"or\"",
    "\"and\"",
    "\"not\"",
    "\"men\"",
    "\"true\"",
    "\"false\"",
    "\"num\"",
    "\"bool\"",
    "\"&&\"",
    "<token of kind 16>",
    "<token of kind 17>",
    "\";\"",
    "<numeroReal>",
    "<identificador>",
    "\"=\"",
    "\"-\"",
    "\"+\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"*\"",
    "\"/\"",
  };

}
