
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Sat Jun 23 17:21:39 CEST 2018
//----------------------------------------------------

package cup;

/** CUP generated class containing symbol constants. */
public class Lexicon {
  /* terminals */
  public static final int GEQ = 7;
  public static final int AND = 11;
  public static final int IS = 4;
  public static final int LT = 8;
  public static final int PLUS = 14;
  public static final int OR = 12;
  public static final int NOT = 13;
  public static final int TRUE = 21;
  public static final int GT = 6;
  public static final int ID = 23;
  public static final int NUM = 24;
  public static final int PCL = 19;
  public static final int POP = 18;
  public static final int EOL = 3;
  public static final int EOF = 0;
  public static final int DIV = 17;
  public static final int FALSE = 22;
  public static final int MINUS = 15;
  public static final int error = 1;
  public static final int EQ = 5;
  public static final int LREAL = 20;
  public static final int BOOL = 25;
  public static final int LEQ = 9;
  public static final int SPROG = 2;
  public static final int MUL = 16;
  public static final int NEQ = 10;
}

