package alex;

public enum ClaseLexica {
	ENT, REAL, MAS, MENOS, POR, DIV, PAP, PCIERRE, IGUAL, EXP, AMPERSAND, IGUALIGUAL, MAYORIGUAL, DISTINTO, PUNTOCOMA, MAYOR, MENOR,
	EOF, MENORIGUAL, TRUE, FALSE, NUM, BOOL, IDEN;
}
