
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Jun 11 16:59:12 CEST 2018
//----------------------------------------------------

package asint;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PCIERRE = 13;
  public static final int AND = 20;
  public static final int SEP_ENTRADA = 16;
  public static final int MAYOR_IGUAL_QUE = 9;
  public static final int OR = 21;
  public static final int IGUAL = 10;
  public static final int FIN_LINEA = 17;
  public static final int MENOR_IGUAL_QUE = 8;
  public static final int PAPERTURA = 12;
  public static final int SUMA = 2;
  public static final int NOT = 22;
  public static final int VARIABLE = 18;
  public static final int MAYOR_QUE = 7;
  public static final int NUM = 14;
  public static final int MENOR_QUE = 6;
  public static final int IGUAL_IGUAL = 23;
  public static final int DISTINTO = 11;
  public static final int EOF = 0;
  public static final int DIV = 5;
  public static final int error = 1;
  public static final int BOOL = 15;
  public static final int MUL = 4;
  public static final int VALOR = 19;
  public static final int RESTA = 3;
}

