package alex;

public enum ClaseLexica {
	SUMA, RESTA, MUL, DIV, MENOR_QUE, MAYOR_QUE, MENOR_IGUAL_QUE, MAYOR_IGUAL_QUE,
	IGUAL, DISTINTO, PAPERTURA, PCIERRE, NUM, BOOL, SEP_ENTRADA, FIN_LINEA, 
	VARIABLE, TRUE, FALSE, VALOR, LETRA, DIGITO, EOF, AND, OR, NOT, IGNORABLE, 
	IGUAL_IGUAL
}
